export interface ToolProperties {
    externalIsCleanState?: any;
    externalCasingConditionState?: any;
    externalPlugState?: any;
    externalWireState?: any;
    externalBendProtectorState?: any;
    externalCompleteButtonsState?: any;
    externalCompleteHandlesState?: any;
    externalOuterCoverState?: any;
    externalLeakageState?: any;
    internalBendProtectorState?: any;
    internalPlugWireState?: any;
    internalElectricEqState?: any;
    internalEngineDirtyState?: any;
    internalCommutatorState?: any;
    internalBearingsState?: any;
    mesauredResistanceState: number;
    requiredResistanceState: number;
    isolateResistanceState: boolean;
    currentValue: number;
    voltageValue: number;
    protectiveConductorResistance: number;
    permissibleProtectiveConductorResistance: number;
    protectionCircuitState: boolean;
    idleRunState?: any;
    dateOfService: Date;
    remarks: string;
    isValid: boolean;
}